version: '3.9'
services:
  backend:
    build:
      context: ./E REPORTING-IA-JAVA/backend
      dockerfile: Dockerfile
    container_name: reporting-backend
    ports:
      - "8080:8080"
    networks:
      - reporting_net
  frontend:
    build:
      context: ./E REPORTING-IA-JAVA/frontend
      dockerfile: Dockerfile
    container_name: reporting-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - reporting_net
networks:
  reporting_net:
    driver: bridge