services:
  backend:
    build:
      context: ./E REPORTING-IA-JAVA/backend
      dockerfile: Dockerfile
    container_name: reporting-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - reporting_net
  frontend:
    build:
      context: ./E REPORTING-IA-JAVA/frontend
      dockerfile: Dockerfile
    container_name: reporting-frontend
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    depends_on:
      - backend
    environment:
      - DISABLE_AUTH=true
    networks:
      - reporting_net
networks:
  reporting_net:
    driver: bridge