services:
  - type: web
    name: reporting-ia
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 8081