<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // PAYS UEMOA
            [
                'code' => 'BJ',
                'name' => 'Bénin',
                'name_fr' => 'République du Bénin',
                'name_en' => 'Benin',
                'capital' => 'Porto-Novo',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+229',
                'flag_emoji' => '🇧🇯',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'en'],
                'regulatory_framework' => [
                    'Code OHADA',
                    'Directives UEMOA',
                    'Loi portant organisation de l\'administration publique'
                ],
                'compliance_requirements' => [
                    'SYSCOHADA',
                    'Directives BCEAO',
                    'Code des marchés publics UEMOA'
                ],
                'document_templates' => [
                    'budget_annuel_societe_etat',
                    'etats_financiers_syscohada',
                    'plan_passation_marches_uemoa'
                ],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'République du Bénin, traditions vodoun et diversité culturelle',
                    'economic_focus' => 'Agriculture, commerce transfrontalier, port de Cotonou',
                    'regulatory_emphasis' => 'Conformité UEMOA et réformes administratives'
                ],
                'status' => 'active',
                'metadata' => [
                    'fiscal_start_month' => 1,
                    'fiscal_end_month' => 12,
                    'main_economic_sectors' => ['Agriculture', 'Commerce', 'Transport'],
                    'development_priorities' => ['Digitalisation', 'Infrastructure', 'Éducation']
                ]
            ],

            [
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'name_fr' => 'Burkina Faso',
                'name_en' => 'Burkina Faso',
                'capital' => 'Ouagadougou',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+226',
                'flag_emoji' => '🇧🇫',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'moore', 'dioula'],
                'regulatory_framework' => [
                    'SYSCOHADA révisé 2019',
                    'Code des sociétés commerciales',
                    'Code des marchés publics'
                ],
                'compliance_requirements' => [
                    'SYSCOHADA',
                    'Directives UEMOA',
                    'Comptabilité des matières',
                    'Gouvernance d\'entreprise'
                ],
                'document_templates' => [
                    'budget_annuel_societe_etat',
                    'etats_financiers_syscohada',
                    'plan_passation_marches_uemoa',
                    'inventaire_patrimoine',
                    'rapport_gestion_ca'
                ],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Pays des hommes intègres, diversité ethnique et culturelle',
                    'economic_focus' => 'Agriculture, mines d\'or, élevage, coton',
                    'regulatory_emphasis' => 'Bonne gouvernance, transparence, développement durable'
                ],
                'status' => 'active',
                'metadata' => [
                    'fiscal_start_month' => 1,
                    'fiscal_end_month' => 12,
                    'main_economic_sectors' => ['Agriculture', 'Mines', 'Élevage', 'Commerce'],
                    'development_priorities' => ['Sécurité', 'Infrastructure', 'Éducation', 'Santé'],
                    'special_entities' => ['SONABEL', 'ONEA', 'SONAPOST', 'FASO BAARA']
                ]
            ],

            [
                'code' => 'CI',
                'name' => 'Côte d\'Ivoire',
                'name_fr' => 'République de Côte d\'Ivoire',
                'name_en' => 'Ivory Coast',
                'capital' => 'Yamoussoukro',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+225',
                'flag_emoji' => '🇨🇮',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'en'],
                'regulatory_framework' => [
                    'Code des investissements',
                    'Loi sur les sociétés commerciales',
                    'Réglementation BRVM'
                ],
                'compliance_requirements' => [
                    'SYSCOHADA',
                    'Normes BRVM',
                    'Réglementation bancaire BCEAO'
                ],
                'document_templates' => [
                    'budget_annuel_societe_etat',
                    'etats_financiers_syscohada',
                    'rapport_activites_brvm'
                ],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Locomotiva économique de l\'Afrique de l\'Ouest',
                    'economic_focus' => 'Cacao, café, pétrole, industrie, services financiers',
                    'regulatory_emphasis' => 'Marché financier BRVM, excellence économique'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'ML',
                'name' => 'Mali',
                'name_fr' => 'République du Mali',
                'name_en' => 'Mali',
                'capital' => 'Bamako',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+223',
                'flag_emoji' => '🇲🇱',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'bambara'],
                'status' => 'active'
            ],

            [
                'code' => 'NE',
                'name' => 'Niger',
                'name_fr' => 'République du Niger',
                'name_en' => 'Niger',
                'capital' => 'Niamey',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+227',
                'flag_emoji' => '🇳🇪',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'hausa'],
                'status' => 'active'
            ],

            [
                'code' => 'SN',
                'name' => 'Sénégal',
                'name_fr' => 'République du Sénégal',
                'name_en' => 'Senegal',
                'capital' => 'Dakar',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+221',
                'flag_emoji' => '🇸🇳',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'wolof', 'en'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Porte d\'entrée de l\'Afrique de l\'Ouest, carrefour culturel',
                    'economic_focus' => 'Services, pêche, agriculture, phosphates, tourisme',
                    'regulatory_emphasis' => 'Hub financier régional, innovation technologique'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'TG',
                'name' => 'Togo',
                'name_fr' => 'République Togolaise',
                'name_en' => 'Togo',
                'capital' => 'Lomé',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+228',
                'flag_emoji' => '🇹🇬',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'ewe', 'kabye'],
                'status' => 'active'
            ],

            [
                'code' => 'GW',
                'name' => 'Guinée-Bissau',
                'name_fr' => 'République de Guinée-Bissau',
                'name_en' => 'Guinea-Bissau',
                'capital' => 'Bissau',
                'currency_code' => 'XOF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+245',
                'flag_emoji' => '🇬🇼',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'UEMOA',
                'is_uemoa_member' => true,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['pt'],
                'business_languages' => ['pt', 'fr', 'crioulo'],
                'status' => 'active'
            ],

            // PAYS CEMAC
            [
                'code' => 'CM',
                'name' => 'Cameroun',
                'name_fr' => 'République du Cameroun',
                'name_en' => 'Cameroon',
                'capital' => 'Yaoundé',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+237',
                'flag_emoji' => '🇨🇲',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr', 'en'],
                'business_languages' => ['fr', 'en'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Afrique en miniature, bilinguisme français-anglais',
                    'economic_focus' => 'Pétrole, agriculture, forêt, industrie manufacturière',
                    'regulatory_emphasis' => 'Système CEMAC, diversification économique'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'GA',
                'name' => 'Gabon',
                'name_fr' => 'République Gabonaise',
                'name_en' => 'Gabon',
                'capital' => 'Libreville',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+241',
                'flag_emoji' => '🇬🇦',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr'],
                'status' => 'active'
            ],

            [
                'code' => 'TD',
                'name' => 'Tchad',
                'name_fr' => 'République du Tchad',
                'name_en' => 'Chad',
                'capital' => 'N\'Djaména',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+235',
                'flag_emoji' => '🇹🇩',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr', 'ar'],
                'business_languages' => ['fr', 'ar'],
                'status' => 'active'
            ],

            [
                'code' => 'CF',
                'name' => 'République Centrafricaine',
                'name_fr' => 'République Centrafricaine',
                'name_en' => 'Central African Republic',
                'capital' => 'Bangui',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+236',
                'flag_emoji' => '🇨🇫',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'sangho'],
                'status' => 'active'
            ],

            [
                'code' => 'CG',
                'name' => 'République du Congo',
                'name_fr' => 'République du Congo',
                'name_en' => 'Republic of the Congo',
                'capital' => 'Brazzaville',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+242',
                'flag_emoji' => '🇨🇬',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'lingala'],
                'status' => 'active'
            ],

            [
                'code' => 'GQ',
                'name' => 'Guinée Équatoriale',
                'name_fr' => 'République de Guinée Équatoriale',
                'name_en' => 'Equatorial Guinea',
                'capital' => 'Malabo',
                'currency_code' => 'XAF',
                'currency_name' => 'Franc CFA',
                'currency_symbol' => 'FCFA',
                'phone_prefix' => '+240',
                'flag_emoji' => '🇬🇶',
                'region' => 'Afrique Centrale',
                'sub_region' => 'CEMAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => true,
                'accounting_system' => 'SYSCEBNAC',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['es', 'fr', 'pt'],
                'business_languages' => ['es', 'fr'],
                'status' => 'active'
            ],

            // AUTRES PAYS OHADA (non UEMOA/CEMAC)
            [
                'code' => 'CD',
                'name' => 'République Démocratique du Congo',
                'name_fr' => 'République Démocratique du Congo',
                'name_en' => 'Democratic Republic of the Congo',
                'capital' => 'Kinshasa',
                'currency_code' => 'CDF',
                'currency_name' => 'Franc Congolais',
                'currency_symbol' => 'FC',
                'phone_prefix' => '+243',
                'flag_emoji' => '🇨🇩',
                'region' => 'Afrique Centrale',
                'sub_region' => 'OHADA',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'lingala', 'swahili'],
                'status' => 'active'
            ],

            [
                'code' => 'DJ',
                'name' => 'Djibouti',
                'name_fr' => 'République de Djibouti',
                'name_en' => 'Djibouti',
                'capital' => 'Djibouti',
                'currency_code' => 'DJF',
                'currency_name' => 'Franc Djiboutien',
                'currency_symbol' => 'Fdj',
                'phone_prefix' => '+253',
                'flag_emoji' => '🇩🇯',
                'region' => 'Afrique de l\'Est',
                'sub_region' => 'OHADA',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr', 'ar'],
                'business_languages' => ['fr', 'ar', 'en'],
                'status' => 'active'
            ],

            [
                'code' => 'KM',
                'name' => 'Comores',
                'name_fr' => 'Union des Comores',
                'name_en' => 'Comoros',
                'capital' => 'Moroni',
                'currency_code' => 'KMF',
                'currency_name' => 'Franc Comorien',
                'currency_symbol' => 'FC',
                'phone_prefix' => '+269',
                'flag_emoji' => '🇰🇲',
                'region' => 'Afrique de l\'Est',
                'sub_region' => 'OHADA',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['ar', 'fr', 'comorien'],
                'business_languages' => ['fr', 'ar'],
                'status' => 'active'
            ],

            [
                'code' => 'GN',
                'name' => 'Guinée',
                'name_fr' => 'République de Guinée',
                'name_en' => 'Guinea',
                'capital' => 'Conakry',
                'currency_code' => 'GNF',
                'currency_name' => 'Franc Guinéen',
                'currency_symbol' => 'FG',
                'phone_prefix' => '+224',
                'flag_emoji' => '🇬🇳',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'OHADA',
                'is_uemoa_member' => false,
                'is_ohada_member' => true,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'SYSCOHADA',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['fr'],
                'business_languages' => ['fr', 'soussou', 'peul'],
                'status' => 'active'
            ],

            // AUTRES PAYS AFRICAINS PRIORITAIRES
            [
                'code' => 'NG',
                'name' => 'Nigeria',
                'name_fr' => 'République Fédérale du Nigeria',
                'name_en' => 'Nigeria',
                'capital' => 'Abuja',
                'currency_code' => 'NGN',
                'currency_name' => 'Naira',
                'currency_symbol' => '₦',
                'phone_prefix' => '+234',
                'flag_emoji' => '🇳🇬',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'CEDEAO',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['en'],
                'business_languages' => ['en', 'hausa', 'igbo', 'yoruba'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Géant de l\'Afrique, diversité ethnique et religieuse',
                    'economic_focus' => 'Pétrole, agriculture, technologie, services financiers',
                    'regulatory_emphasis' => 'Standards IFRS, réglementation bancaire avancée'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'GH',
                'name' => 'Ghana',
                'name_fr' => 'République du Ghana',
                'name_en' => 'Ghana',
                'capital' => 'Accra',
                'currency_code' => 'GHS',
                'currency_name' => 'Cedi Ghanéen',
                'currency_symbol' => 'GH₵',
                'phone_prefix' => '+233',
                'flag_emoji' => '🇬🇭',
                'region' => 'Afrique de l\'Ouest',
                'sub_region' => 'CEDEAO',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => true,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['en'],
                'business_languages' => ['en', 'twi', 'ga'],
                'status' => 'active'
            ],

            [
                'code' => 'KE',
                'name' => 'Kenya',
                'name_fr' => 'République du Kenya',
                'name_en' => 'Kenya',
                'capital' => 'Nairobi',
                'currency_code' => 'KES',
                'currency_name' => 'Shilling Kenyan',
                'currency_symbol' => 'KSh',
                'phone_prefix' => '+254',
                'flag_emoji' => '🇰🇪',
                'region' => 'Afrique de l\'Est',
                'sub_region' => 'EAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'july_june',
                'official_languages' => ['en', 'sw'],
                'business_languages' => ['en', 'sw'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Hub technologique de l\'Afrique de l\'Est',
                    'economic_focus' => 'Services financiers, agriculture, tourisme, technologie',
                    'regulatory_emphasis' => 'Innovation fintech, M-Pesa, marché des capitaux'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'ZA',
                'name' => 'Afrique du Sud',
                'name_fr' => 'République d\'Afrique du Sud',
                'name_en' => 'South Africa',
                'capital' => 'Le Cap',
                'currency_code' => 'ZAR',
                'currency_name' => 'Rand Sud-Africain',
                'currency_symbol' => 'R',
                'phone_prefix' => '+27',
                'flag_emoji' => '🇿🇦',
                'region' => 'Afrique Australe',
                'sub_region' => 'SADC',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'april_march',
                'official_languages' => ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
                'business_languages' => ['en', 'af'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Nation arc-en-ciel, économie la plus développée d\'Afrique',
                    'economic_focus' => 'Mines, services financiers, industrie, agriculture',
                    'regulatory_emphasis' => 'JSE, King IV governance, BEE compliance'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'MA',
                'name' => 'Maroc',
                'name_fr' => 'Royaume du Maroc',
                'name_en' => 'Morocco',
                'capital' => 'Rabat',
                'currency_code' => 'MAD',
                'currency_name' => 'Dirham Marocain',
                'currency_symbol' => 'DH',
                'phone_prefix' => '+212',
                'flag_emoji' => '🇲🇦',
                'region' => 'Afrique du Nord',
                'sub_region' => 'Maghreb',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['ar', 'ber'],
                'business_languages' => ['ar', 'fr', 'en'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Pont entre l\'Afrique et l\'Europe, tradition millénaire',
                    'economic_focus' => 'Agriculture, phosphates, textile, tourisme, automobile',
                    'regulatory_emphasis' => 'Standards internationaux, place financière Casablanca'
                ],
                'status' => 'active'
            ],

            [
                'code' => 'EG',
                'name' => 'Égypte',
                'name_fr' => 'République Arabe d\'Égypte',
                'name_en' => 'Egypt',
                'capital' => 'Le Caire',
                'currency_code' => 'EGP',
                'currency_name' => 'Livre Égyptienne',
                'currency_symbol' => 'E£',
                'phone_prefix' => '+20',
                'flag_emoji' => '🇪🇬',
                'region' => 'Afrique du Nord',
                'sub_region' => 'Maghreb',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'july_june',
                'official_languages' => ['ar'],
                'business_languages' => ['ar', 'en', 'fr'],
                'status' => 'active'
            ],

            [
                'code' => 'TN',
                'name' => 'Tunisie',
                'name_fr' => 'République Tunisienne',
                'name_en' => 'Tunisia',
                'capital' => 'Tunis',
                'currency_code' => 'TND',
                'currency_name' => 'Dinar Tunisien',
                'currency_symbol' => 'DT',
                'phone_prefix' => '+216',
                'flag_emoji' => '🇹🇳',
                'region' => 'Afrique du Nord',
                'sub_region' => 'Maghreb',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'LOCAL',
                'fiscal_year_type' => 'calendar',
                'official_languages' => ['ar'],
                'business_languages' => ['ar', 'fr', 'en'],
                'status' => 'active'
            ],

            [
                'code' => 'ET',
                'name' => 'Éthiopie',
                'name_fr' => 'République Fédérale Démocratique d\'Éthiopie',
                'name_en' => 'Ethiopia',
                'capital' => 'Addis-Abeba',
                'currency_code' => 'ETB',
                'currency_name' => 'Birr Éthiopien',
                'currency_symbol' => 'Br',
                'phone_prefix' => '+251',
                'flag_emoji' => '🇪🇹',
                'region' => 'Afrique de l\'Est',
                'sub_region' => 'Corne de l\'Afrique',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'july_june',
                'official_languages' => ['am'],
                'business_languages' => ['am', 'en'],
                'status' => 'active'
            ],

            [
                'code' => 'RW',
                'name' => 'Rwanda',
                'name_fr' => 'République du Rwanda',
                'name_en' => 'Rwanda',
                'capital' => 'Kigali',
                'currency_code' => 'RWF',
                'currency_name' => 'Franc Rwandais',
                'currency_symbol' => 'FRw',
                'phone_prefix' => '+250',
                'flag_emoji' => '🇷🇼',
                'region' => 'Afrique de l\'Est',
                'sub_region' => 'EAC',
                'is_uemoa_member' => false,
                'is_ohada_member' => false,
                'is_ecowas_member' => false,
                'is_cemac_member' => false,
                'accounting_system' => 'IFRS',
                'fiscal_year_type' => 'july_june',
                'official_languages' => ['rw', 'fr', 'en'],
                'business_languages' => ['en', 'fr', 'rw'],
                'ai_prompt_adaptations' => [
                    'cultural_context' => 'Pays des mille collines, transformation remarquable',
                    'economic_focus' => 'Services, ICT, tourisme, agriculture moderne',
                    'regulatory_emphasis' => 'Digitalisation, facilitation des affaires, gouvernance'
                ],
                'status' => 'active'
            ]
        ];

        foreach ($countries as $countryData) {
            Country::updateOrCreate(
                ['code' => $countryData['code']],
                $countryData
            );
        }
    }
}